import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";

export default function Home() {
  return (
    <>
      <Head>
        <title>Columbus app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={`${styles.page}`}>
        <Header />
        <main className={styles.main}>somethiung</main>
      </div>
    </>
  );
}
